### ISSUE TITLE
Wrong credentials

### ISSUE THREAD

**Issue by billidani7** [SoftInstigate/restheart-notes-example#2]
Hi

I use admin for id and changeit for password and I get "Wrong credentials".

**Comment by ujibang** [comment]
Have you changed the ip of restheart in app.js?

Andrea Di Cesare

**Comment by billidani7** [comment]
Yes I have changed with http://localhost:8080 in app.js

Also when I use the

```
http -a admin:changeit PUT http://localhost:8080/rhnedb descr="restheart notes example db"
```

i get this error

```
http: error: ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /rhnedb (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1103f8910>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

this the output of grunt serve command
Running "serve" task

Running "clean:server" (clean) task

> > 0 paths cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:server" (concurrent) task

```
Running "compass:server" (compass) task

Done, without errors.


Execution Time (2015-11-21 12:10:42 UTC)
loading grunt-contrib-compass  65ms  ▇▇ 4%
compass:server                 1.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 95%
Total 1.5s
```

Running "autoprefixer:server" (autoprefixer) task in app.js

Running "connect:livereload" (connect) task
Started connect web server on http://localhost:9000

Running "watch" task
Waiting...

**Comment by ujibang** [comment]
grunt serve starts a web server for static resources (html, css, js). It does bot start restheart.

You need to start restheart process as well.

**Comment by billidani7** [comment]
Restheart process is already running

```
docker logs restheart
[main] INFO  org.restheart.Bootstrapper -RESTHeartstarted**********************************************
```

**Comment by ujibang** [comment]
Are you running docker on windows or macos? In this case you need to figure out the ip of the doker machine (or boot2docker) and set it in the variabe in app.js

https://docs.docker.com/machine/reference/ip/

**Comment by billidani7** [comment]
I am running docker on Mac OS X Yosemite.
When I open the "Docker quick start terminal" i can see my ip.
`docker is configured to use the default machine with IP 192.168.99.100`

I have set this ip in app.js (before was localhost and I had the same problem)
`var RESTHEART_URL = "http://192.168.99.100:8080";`

Then in "Docker quick start terminal" I use the grunt serve. The server initialised and started with no errors

Unfortunately, I can't log in with the credentials

**Comment by ujibang** [comment]
can you try user _admin_ and password _admin_ (not _changeit_)

I just figured out that the restheart docker image comes with a different _security.yml_ file than the standard distribution.

In any case, I'm updating the docker image to match the default password.

**Comment by ujibang** [comment]
Hi I have updated the docker image; run again to update it:

```
$ docker pull softinstigate/restart
```

Now password is _changeit_

In summary:
- run mongo container:

```
docker run -d --name mongodb mongo:3.0
```
- run restheart container (the --rm options deletes the container on exit, safe since restheart is stateless):

```
docker run -i -t --rm -p 8080:8080 --name restheart --link mongodb:mongodb softinstigate/restheart
```
- make sure the variable _RESTHEART_URL_ in app/scripts/app.js matches the ip of the docker machine that can be obtained with

```
docker-machine ip default
```
- start http server

```
grunt serve
```
- login with user _admin_ and password _changeit_

**Comment by ujibang** [comment]
I just made a commit to show an error message on the sign-in page if RESTHeart is not running at the specified ip:port

please pull it and retry.
