### ISSUE TITLE
Problem on windows / docker for windows

### ISSUE THREAD

**Issue by andrejpodgorsek** [SoftInstigate/restheart-notes-example#3]
Hi.

what am I doing wrong?

> λ grunt serve
Running "serve" task

Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:server" (concurrent) task
    Warning: Running "compass:server" (compass) task
Warning: not found: compass Use --force to continue.

Aborted due to warnings.

Execution Time (2017-05-03 10:34:16 UTC+2)
loading tasks                   9ms  █████ 16%
loading grunt-contrib-compass  30ms  █████████████████ 54%
compass:server                 16ms  █████████ 29%
Total 56ms Use --force to continue.

    Aborted due to warnings.

Execution Time (2017-05-03 10:34:16 UTC+2)
loading tasks                  9ms  █ 1%
loading grunt-contrib-clean    8ms  █ 1%
wiredep:app                  167ms  ███████████ 23%
wiredep:test                  28ms  ██ 4%
wiredep:sass                  33ms  ███ 5%
loading grunt-concurrent       8ms  █ 1%
concurrent:server            464ms  ██████████████████████████████ 64%
Total 729ms

**Comment by mkjsix** [comment]
Sorry @andrejpodgorsek, why did you open an issue about grunt here? I'm confused...

**Comment by andrejpodgorsek** [comment]
Hey, sorry. Just seen the error on your project.

The issue is solved with --force param.

**Comment by mkjsix** [comment]
Yes, but there's an undocumented dependency from compass, we're having a look (not touching this repo since ages...)

**Comment by mkjsix** [comment]
I've edited the documentation, it was referring to old versions of docker. Now if you have installed docker for Mac or Windows, you can directly point to localhost.

I'm now closing this issue, feel free to re-open in case.
